### PR TITLE
Change license to the more permissive ISC

### PR DESCRIPTION
**Pull request by simo5**
This change is not sudden, I have been thinking about relicensing this
project for quite a while.
The main trigger is that I received a couple of requests for a more
permissive license, but the real reason is that I always felt it at
odds that a module that is targeted to be loaded by MIT/Krb5's gssapi
library had such a widely different license.
It may give rise to misunderstandings as well as create undue burden
on users to figure out license compatibility with their applications
(proven in fact by the requests to relicense).

### CODE REVIEW

**Comment by simo5** [comment]
@dwmw2 PTAL given you are the only other contributor with more than a few lines

**Comment by dwmw2** [comment]
Anything under my own address is fine. If it was sent from an @intel.com address I'll need to clear it with them first.

**Comment by dwmw2** [comment]
Intel too slow to respond. Given that I made the decision to submit this on my own at the time, and would have done so under the proposed licence without seeking further approval, I'd suggest you just go ahead even though I am no longer working for them.

**Comment by simo5** [comment]
Thank you.

**Pull request merged**
