### PR TITLE
Allow to gss_wrap even if NEGOTIATE_SEAL is not negotiated

### LINKED ISSUE #77: gss_wrap/gss_unwrap should work on connection without NEGOTIATE_SEAL
Let's start with a bit of a background.

RFC 2222 originally specified the GSSAPI SASL mechanism for authentication. It didn't specifically tie the mechanism to Kerberos unlike the later RFC 4752 revision. As a last step of the authentication exchange the server sends a token with supported protection schemes and maximum token size to the client. This is encoded with `GSS_Wrap` API with `conf_flag == 0`. The client decodes it with `GSS_Unwrap`, chooses the preferred protection for rest of communication, and then encodes the reply with `GSS_Wrap` and sends it back to server.

Microsoft Exchange implements this mechanism for authentication to SMTP, IMAP and POP3 services. It works with Negotiate, Kerberos and NTLM protocols. The NTLM one is particularly tricky because the semantics for `GSS_Warp`/`GSS_Unwrap` are not fully covered by the specifications. So I went ahead, set up an Exchange server with Windows AD and tested what is really sent on the wire.

---

In case NEGOTIATE_SEAL is negotiated in the initial authentication the gss-ntlmssp library is already interoperable. The `conf_flag` is ignored (not a surprise since NTLM doesn't have a way to transmit the flag on the wire like Kerberos does), sealing and signing is applied.

In case NEGOTIATE_SEAL is NOT negotiated and NEGOTIATE_SIGN+NEGOTIATE_KEY_EXHANGE were negotiated the tokens should still be sealed with the computed key and signed. gss-ntlmssp currently doesn't [implement that](https://github.com/gssapi/gss-ntlmssp/blob/a898099deccac30a56c3af97f255045f86f5c36f/src/ntlm_crypto.c#L905-L908).

I didn't check the behavior for other flag combinations yet. I am not particularly interested in them because anything without MIC calculation downgrades the security beyond a point where latest Windows versions may reject it.

---

Notably, I would expect the `GSS_Wrap` behavior to align with the behavior of the `EncryptMessage` (NTLM) API on Windows with the data buffer not having the `SECBUFFER_READONLY` flag and the `conf_flag` flag matching the `SECQOP_WRAP_NO_ENCRYPT` flag. That means always sealing the data (at least for NTLM2 w/ key exchange) and ignoring the `conf_flag` flag.

Confusingly, the [NegotiateStream specification](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-NNS/[MS-NNS].pdf) is also defined in terms of `GSS_Wrap`/`GSS_Unwrap` methods. Unlike the SMTP authentication it behaves differently on NTLM where it sends the messages as `<signature token><unsealed message>` if `NEGOTIATE_SEAL` was not specified. This difference is caused by a special NTLM code path in the `NegotiateStream` code that passes the `SECBUFFER_READONLY` flag to the `EncryptMessage`/`DecryptMessage` methods. The equivalent GSSAPI transformation is to call `gss_get_mic` to produce the `<signature token>` and use `gss_verify_mic` to verify it. This cannot be expressed with `GSS_Wrap`/`GSS_Unwrap` directly.

### PR DESCRIPTION
**Pull request by simo5**
Fixes #77

### CODE REVIEW

**Comment by simo5** [comment]
@filipnavara do you think you can check if this removes the need for a workaround in DOTNET ?

**Comment by filipnavara** [comment]
LGTM. I'll run my tests tomorrow morning when I get back to office.

**Comment by filipnavara** [comment]
Passed the .NET SMTP tests with the removed workaround. 

Before (main):
```
  ===========================================================================================================
  /workspaces/runtime/artifacts/bin/System.Net.Mail.Functional.Tests/Debug/net7.0-unix /workspaces/runtime/src/libraries/System.Net.Mail/tests/Functional
    Discovering: System.Net.Mail.Functional.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Net.Mail.Functional.Tests (found 154 of 156 test cases)
    Starting:    System.Net.Mail.Functional.Tests (parallel test collections = on, max threads = 8)
      System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication [FAIL]
        Assert.Equal() Failure
        Expected: GSSAPI
        Actual:   login
        Stack Trace:
          /workspaces/runtime/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs(577,0): at System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication()
             at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
          /workspaces/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(64,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
    Finished:    System.Net.Mail.Functional.Tests
  === TEST EXECUTION SUMMARY ===
     System.Net.Mail.Functional.Tests  Total: 249, Errors: 0, Failed: 1, Skipped: 0, Time: 8.038s
```

After (PR):
```
  ===========================================================================================================
  /workspaces/runtime/artifacts/bin/System.Net.Mail.Functional.Tests/Debug/net7.0-unix /workspaces/runtime/src/libraries/System.Net.Mail/tests/Functional
    Discovering: System.Net.Mail.Functional.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Net.Mail.Functional.Tests (found 154 of 156 test cases)
    Starting:    System.Net.Mail.Functional.Tests (parallel test collections = on, max threads = 8)
    Finished:    System.Net.Mail.Functional.Tests
  === TEST EXECUTION SUMMARY ===
     System.Net.Mail.Functional.Tests  Total: 249, Errors: 0, Failed: 0, Skipped: 0, Time: 7.040s
```

**Review by filipnavara — APPROVED** [review]

**Comment by simo5** [comment]
Great!
Thanks.

**Pull request merged**
