### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.fedoraproject.org/projects/gss-ntlmssp/master/) for gss-ntlmssp/main.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by frozencemetery — CHANGES_REQUESTED** [review]
Weblate does have Korean translations, but the bot appears to be proposing empty strings, which isn't right.

**Comment by simo5** [comment]
@frozencemetery sounds like the PR was fixed and there are translations.
I do not speak Korean, so i ran it through Google translate. The translations back are not too far from the English string, so I guess I can approve.

**Review by simo5 — APPROVED** [review]
LGTM

**Review by frozencemetery — COMMENTED** [review]
Agreed, it does look fixed now.  I withdraw my objection :)

However, I don't speak Korean and I'm not sure I know anyone who does, so I can't vouch for their correctness either.

**Comment by simo5** [comment]
Going to merge, let's hope for the best :-D

**Pull request merged**
