### PR TITLE
Fix hostbased name

### LINKED ISSUE #63: Service name from SPN is incorrectly dropped
The SPN named imported using GSS_C_NT_HOSTBASED_SERVICE drops the service name (https://github.com/gssapi/gss-ntlmssp/blob/9b6493b1419d615e347d67c636fd238aa4d0f780/src/gss_names.c#L297-L300). That's not in line with other NTLM implementations, including Windows, which preserve it. The other implementations simply convert the `SERVICE@HOST` format into `SERVICE/HOST` format which is the included in full in the AVID structure (MsvAvTargetName).

### PR DESCRIPTION
**Pull request by simo5**
Fixes #63

### CODE REVIEW

**Comment by simo5** [comment]
@filipnavara hopefully this addresses the SPN issue.
However it would be really nice to check that there are no regressions against a modern windows server given that I am fiddling with fields of the Traget Info that I haven't really touched before.

**Review by filipnavara — APPROVED** [review]
Tested against Windows Server 2022 by HTTP Negotiate. Also tested against my locally running unit test with custom NTLM server and the SPN was echoed correctly through the authentication flow.

**Comment by simo5** [comment]
Nice,
I'm going to add just a couple of tests and then push it to master.

**Comment by simo5** [comment]
Glad I added tests, found incorrect behavior with names like "", "@", "@foo.bar", ...
@filipnavara do you have any tests with names like the above? ^^

**Comment by filipnavara** [comment]
> @filipnavara do you have any tests with names like the above? ^^

Not at the moment but I will try it and cross check with other implementations!

**Comment by simo5** [comment]
Alright, in the meanwhile I'll push this code as is, can always correct later if anything comes up about current behavior vs other implementations.

**Comment by simo5** [comment]
Please note that the implementation will not currently set Traget Name in Target Info if a gss name is obtained that only includes a name and not a full spn ...

**Pull request merged**
